{
 "title": "Sample Node.js Application",
 "tags": [
  "app",
  "node.js",
  "backend"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(nodejs_active_requests_total, job)"
   },
   {
    "name": "instance",
    "query": "label_values(nodejs_active_requests_total{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "5xx Error Rate (30s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", statuscode=~\"5..\"}[30s]) / rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[30s])"
    }
   ]
  },
  {
   "title": "Throughput By Method (30s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[30s])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Throughput By Status (30s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[30s])) by (statuscode)",
     "legendFormat": "{{ statuscode }}"
    }
   ]
  },
  {
   "title": "4xx Error Rate (30s)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\", statuscode=~\"4..\"}[30s])) / sum(rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[30s]))"
    }
   ]
  },
  {
   "title": "Response Time (30s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sample_app_histogram_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[30s])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(sample_app_histogram_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[30s])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(sample_app_histogram_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "sum(rate(sample_app_histogram_request_duration_seconds_sum{job=\"$job\", instance=\"$instance\"}[30s])) by (instance, job) / sum(rate(sample_app_histogram_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[30s])) by (instance, job)",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Service Level Objectives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Error Budget Burndown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "remaining" }
   ],
   "targets": [
    {
     "expr": "job_slo_id:error_budget_remaining:1w",
     "legendFormat": "{{ slo_id }}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptor Usage",
     "type": "singlestat",
     "description": "Current percentage of file descriptors being used by the app.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(process_open_fds{job=\"$job\", instance=\"$instance\"}) / sum(process_max_fds{job=\"$job\", instance=\"$instance\"}) * 100"
      }
     ]
    },
    {
     "title": "Resident Memory (max)",
     "type": "graph",
     "description": "Resident memory used by the NodeJS process.",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"})",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Active Handles (max)",
     "type": "singlestat",
     "description": "Number of active handles.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(nodejs_active_handles_total{job=\"$job\", instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Event Loop Lag",
     "type": "graph",
     "description": "Event loop lag by instance.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_eventloop_lag_seconds{job=\"$job\", instance=\"$instance\"}[30s]) * 120",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU usage by instance.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[30s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap Total Size (avg)",
     "type": "graph",
     "description": "Heap total size by type.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(nodejs_heap_space_size_total_bytes{job=\"$job\", instance=\"$instance\"}) by (space)",
       "legendFormat": "{{ space }}"
      }
     ]
    },
    {
     "title": "Heap Available Size (avg)",
     "type": "graph",
     "description": "Available heap by type.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(nodejs_heap_space_size_available_bytes{job=\"$job\", instance=\"$instance\"}) by (space)",
       "legendFormat": "{{ space }}"
      }
     ]
    },
    {
     "title": "Heap Used Size (avg)",
     "type": "graph",
     "description": "Heap usage by type.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "avg(nodejs_heap_space_size_used_bytes{job=\"$job\", instance=\"$instance\"}) by (space)",
       "legendFormat": "{{ space }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Run (2m)",
     "type": "graph",
     "description": "Number of GC runs per minute.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "run/m" }
     ],
     "targets": [
      {
       "expr": "increase(nodejs_gc_runs_total{job=\"$job\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{ gctype }}"
      }
     ]
    },
    {
     "title": "GC Pause (2m avg)",
     "type": "graph",
     "description": "Average GC pause per run.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_pause_seconds_total{job=\"$job\", instance=\"$instance\"}[30s])",
       "legendFormat": "{{ gctype }}"
      }
     ]
    },
    {
     "title": "Reclaimed Bytes (2m avg)",
     "type": "graph",
     "description": "Average amount of memory reclaimed per GC run.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(nodejs_gc_reclaimed_bytes_total{job=\"$job\", instance=\"$instance\"}[30s])",
       "legendFormat": "{{ gctype }}"
      }
     ]
    }
   ]
  }
 ]
}